kind: ReplicaSet
apiVersion: apps/v1
metadata:
 name: nginx-replicaset
 namespace: nginx-namespace
spec:
 replicas: 2
 selector: 
   matchLabels:
     app: nginx-rep-pod
 template:
   metadata:
      name: nginx-rep-template
      labels: 
        app: nginx-rep-pod
   spec:
     containers:
     - name: nginx-container
       image: nginx:latest
       ports:
       - containerPort: 80

