apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-dep
  template:
    metadata:
      labels:
        app: apache-dep
    spec:
      containers:
      - name: apache-container
        image: httpd:2.4
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: stress
        image: polinux/stress
        command: ["stress"]                        # 👈 explicitly run stress
        args: ["--cpu", "2", "--timeout", "300s"]  # 👈 pass arguments
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m

